version: "3.9"
networks:
  localdev:
    external: true  
services:
  api:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5080:5080"
    networks:
      - localdev
    restart: unless-stopped
